name: Notify Discord

on:
  push:
    branches: [ v2 ]
  pull_request:
    types: [ opened, edited, closed ]
  issues:
    types: [ opened, edited, closed ]

jobs:
  notify:
    uses: ririf4/Actions/.github/workflows/github-to-discord.yml@main
    with:
      repo_name: ${{ github.repository }}
      branch_name: ${{ github.ref_name }}
      event_type: >-
        ${{
          github.event_name == 'push' && 'commit' ||
          github.event_name == 'pull_request' && 'pull-request' ||
          github.event_name == 'issues' && 'issues' ||
          ''
        }}
      commit_sha: ${{ github.sha }}
      commit_message: ${{ github.event.head_commit.message }}
      commit_author: ${{ github.actor }}
      pr_title: ${{ github.event.pull_request.title }}
      pr_body: ${{ github.event.pull_request.body }}
      pr_url: ${{ github.event.pull_request.html_url }}
      pr_number: ${{ github.event.pull_request.number }}
      pr_author: ${{ github.event.pull_request.user.login }}
      pr_state: ${{ github.event.pull_request.state }}
      pr_merged: ${{ github.event.pull_request.merged }}
      issue_title: ${{ github.event.issue.title }}
      issue_body: ${{ github.event.issue.body }}
      issue_url: ${{ github.event.issue.html_url }}
      issue_number: ${{ github.event.issue.number }}
      issue_author: ${{ github.event.issue.user.login }}
      issue_state: ${{ github.event.action }}
    secrets: inherit
